<?php
/**
 * @file
 * granola_taxonomy2.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function granola_taxonomy2_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Cinnamon',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1703ede3-f4c2-4d8f-a383-6cc1c3754ab4',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Maple syrup',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '227279a5-8e5f-4a85-81db-6c2efcdf876c',
    'vocabulary_machine_name' => 'sweeteners',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 150,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Walnuts',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '294ef64a-2126-4f42-a7b8-7974524b6258',
    'vocabulary_machine_name' => 'nuts',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Coconut extract',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2b26dddf-0273-48d5-881a-6cbf5b79cc39',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rolled oats',
    'description' => 'Your standard whole grain granola base.',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2f02d776-3723-4857-a98f-61e24ffc58e4',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 0,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Brown rice flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '35c61f28-a051-4e51-8c7a-144ba02fce89',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Nutmeg',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '39110a42-3cd7-4673-a836-9c44d1c5c9f7',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Almonds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3bc438c5-97a7-4f9a-9675-1408af79fbff',
    'vocabulary_machine_name' => 'nuts',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Pecans',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4087748a-f353-4659-a693-69df34dfa375',
    'vocabulary_machine_name' => 'nuts',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Olive oil',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4e7e962e-70fa-43bc-8c1d-58076da09ff5',
    'vocabulary_machine_name' => 'oils_fats',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Quinoa flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '51888d65-81c0-42cf-a7b3-54430fba13b8',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Sugar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5821652d-65e5-427c-98fa-ab65d47fc2ce',
    'vocabulary_machine_name' => 'sweeteners',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 0,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Almond extract',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '64fa4a7c-b9f3-4841-bfa9-8dbd2eb1e1eb',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 0,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cashews',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '76f07015-6a8d-461e-b79f-135b29600f74',
    'vocabulary_machine_name' => 'nuts',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Millet flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8406c17d-0e08-4a58-8289-a3d67f01eddc',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Coconut oil',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '97ba360f-d938-4388-962a-70d56a25a827',
    'vocabulary_machine_name' => 'oils_fats',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 100,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Kamut flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9bf90b3c-fbb2-402f-a76b-eb0933634363',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Crickets',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9d4b32dd-8d20-4b99-8a01-90aed187385f',
    'vocabulary_machine_name' => 'bird_food',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vegetable oil',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a24ee7f0-41cd-4686-8d47-21a5f41ffc42',
    'vocabulary_machine_name' => 'oils_fats',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 0,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rolled barley flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ad8cb73f-8804-43ac-ad89-b673f0349670',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Dates',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b24e60ea-1d7b-4500-97c9-34803a6ceb84',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 100,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Sesame seeds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b8fbf3a8-b13f-4b11-9cb0-0a03a721383b',
    'vocabulary_machine_name' => 'bird_food',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 100,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Pumpkin seeds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b9247247-db32-4928-9073-987cfc9185cf',
    'vocabulary_machine_name' => 'bird_food',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Apples',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c03f1853-dd38-4f43-8fe6-b6588fa76621',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Apricots',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c3ea26a2-2572-4ec6-9b86-743978a858f4',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 100,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vanilla extract',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cc477f9d-9603-47d9-b84e-48ed7abe5f55',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ginger',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd700fd98-5830-4c01-9b03-c5829871d9f1',
    'vocabulary_machine_name' => 'flavorings_and_spices',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Honey',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd704c750-9f11-443e-9fe3-74d02939f169',
    'vocabulary_machine_name' => 'sweeteners',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 125,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cherries',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd7d2dfb3-8007-4b9d-89b4-41f5f7f52378',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rye flakes',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e14771c9-136e-465a-9184-7390c785b125',
    'vocabulary_machine_name' => 'grains',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Flax seeds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e812cbbf-ce8a-4e3f-bbad-5d598ea368d5',
    'vocabulary_machine_name' => 'bird_food',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Brown sugar',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'eac00d87-4341-487f-99c9-7a97641e60c0',
    'vocabulary_machine_name' => 'sweeteners',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Butter',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ebc1c56b-96ce-496c-8918-28854621bb64',
    'vocabulary_machine_name' => 'oils_fats',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Peanuts',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ee4fb488-7d16-41e0-a128-14772320f2f6',
    'vocabulary_machine_name' => 'nuts',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cranberries',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f4ed00f3-0065-40e2-a6e5-9ee97101fbd2',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Shredded coconut',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f5c9272a-aa63-48d7-a242-723e1ebeb7ab',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 75,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Sunflower seeds',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f814b629-7815-4915-b743-05a8baca97ed',
    'vocabulary_machine_name' => 'bird_food',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 50,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Blueberries',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f89d1c2f-5f5b-45af-92f6-8be28ab3af08',
    'vocabulary_machine_name' => 'dried_fruit',
    'field_price' => array(
      'und' => array(
        0 => array(
          'amount' => 25,
          'currency_code' => 'USD',
          'data' => array(
            'components' => array(),
          ),
        ),
      ),
    ),
  );
  return $terms;
}
